saw_mate/card_decks/urls.py
from django.urls import path
from card_decks import views
app_name = 'carddecks'

urlpatterns = [
    path('carddeck_add/', views.carddeck_add, name='carddeck_add'),
    path('carddeck_change/', views.carddeck_change, name='carddeck_change'),
    path('carddeck_remove/', views.carddeck_remove, name='carddeck_remove'),
    path('cardset_create/', views.cardset_create, name='cardset_create'),
    path('cardset_add/', views.cardset_add, name='cardset_add'),
    path('cardset_change/', views.cardset_change, name='cardset_change'),
    path('cardset_activate/', views.cardset_activate, name='cardset_activate'),
    path('cardset_remove/', views.cardset_remove, name='cardset_remove'),
    path('setitem_remove/', views.setitem_remove, name='setitem_remove'),
]

saw_mate/main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),

]

saw_mate/saw_mate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from saw_mate import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("cards.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("carddeck/", include("card_decks.urls", namespace="carddeck")),
    path("game/", include("games.urls", namespace="game")),
]

#для отладки запросов к БД
if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saw_mate/users/urls.py
from django.urls import path
from users import views
app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

saw_mate/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True, verbose_name='Номер телефона')
    achievements = models.CharField(max_length=200, unique=False, blank=True, verbose_name='Достижения')
    statistic = models.CharField(max_length=400, unique=False, null=True, verbose_name='Статистика')
    level = models.SmallIntegerField(default=1, verbose_name='Уровень')
    win = models.SmallIntegerField(default=0, verbose_name='Побед')
    lose = models.SmallIntegerField(default=0, verbose_name='Поражений')
    status = models.BooleanField(default=False, verbose_name='Статус')
    money = models.DecimalField(default=0.00, max_digits=9, decimal_places=2, verbose_name='Деньги')
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = "Пользователи"
    
    def __str__(self):
        return self.username
    

saw_mate/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User

class UserLoginForm(AuthenticationForm):

    #переопрделим стандартные поля формы
    # username = forms.CharField(
    #     label = 'Имя',
    #     widget = forms.TextInput(attrs={"autofocus": True, 
    #                                 'class': 'form-control',
    #                                 'placeholder': 'Введите ваше имя пользователя'})
    # )
    # password = forms.CharField(
    #     label = 'Пароль',
    #     widget = forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                 'class': 'form-control',
    #                                 'placeholder': 'Введите ваш пароль'})
    # )
    #Укороченный вариант
    username = forms.CharField()
    password = forms.CharField()
    #вложенный класс для полей авторизации
    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

saw_mate/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.contrib import auth, messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from carts.models import Cart
from orders.models import Order, OrderItem
from django.db.models import Prefetch
from card_decks.models import CardDeck, Set, SetItem
from cards.models import Products

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            #сессионный ключ неавторизованного пользователя
            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                #уведомление пользователя о входе
                messages.success(request, f"{username}, успешно вошел на сайт")

                #когда авторизуется пользователь с заполненной корзиной по сессионном ключу то привязываем ему корзину
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                #редирект для неавторизованного пользователя
                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            #сессионный ключ неавторизованного пользователя
            session_key = request.session.session_key
            #записываем в переменную введенные при регистрации данные
            user = form.instance
            #делаем автовход по сохраненным из формы регистрации данным
            auth.login(request, user)

            #когда регистрируется и авторизуется пользователь с заполненной корзиной по сессионном ключу то привязываем ему корзину
            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f"{user.username}, успешно зарегистрировался и вошел на сайт")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'Home - Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)
#ограничение доступа для неавторизованных пользователей
@login_required
def profile(request):
    # нужно будет добавить фильтр по купленным карточкам как было реализовано в catalog

    # вспоминить как работает
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Пользователь упешно обновлен")
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        #отображение информации пользователя
        form = ProfileForm(instance=request.user)
    #отображение заказов в профиле
    orders = (
        #фильтруем заказы по пользователю
        Order.objects.filter(user=request.user).prefetch_related(
            #класс prefetch - указываем имя дополнительного queryset и формируем его из всех заказов по пользователю и через select_releted всеми товарами привязанными к этим заказам
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        )
        #сортируем полученные элементы по -id - вверху будет последний заказ
        .order_by("-id")
    )
    #отображение наборов карточек в профиле
    sets = (
        Set.objects.filter(user=request.user).prefetch_related(
            Prefetch(
                "setitem_set",
                queryset=SetItem.objects.select_related("product"),
            )
        )
        .order_by("-id")
    )

    # Переделать вывод карточек в наборе
    #передаем карточки героев
    # user_cardsets_hero = {}
    # for set_obj in sets:
    #     filtered_items = list(set_obj.setitem_set.filter(
    #         product__category__name='Персонажи',
    #         quantity__gt=0
    #     ).order_by('-id')[:3])  # Преобразуем QuerySet в список

    #     # Если filtered_items содержит менее 3 элементов, добавляем пустые заглушки
    #     if len(filtered_items) < 3:
    #         empty_count = 3 - len(filtered_items)

    #         if Products.objects.filter(name="empty").exists():
    #             for i in range(empty_count):
    #                 empty_set_obj = SetItem()
    #                 # Задаем временные PK для каждой заглушки
    #                 empty_set_obj.pk = i
    #                 empty_set_obj.product = Products.objects.get(name="empty")
    #                 #empty_set_obj.product.category.name = default_product.category.name
    #                 empty_set_obj.set_id = set_obj.id
    #                 empty_set_obj.item_id = i
    #                 empty_set_obj.quantity = 0
    #                 filtered_items.append(empty_set_obj)
    #         else:
    #             for i in range(empty_count):
    #                 empty_set_obj = SetItem()
    #                 # Задаем временные PK для каждой заглушки
    #                 empty_set_obj.pk = i
    #                 # empty_set_obj.product = default_product
    #                 #empty_set_obj.product.category.name = default_product.category.name
    #                 empty_set_obj.set_id = set_obj.id
    #                 empty_set_obj.item_id = i
    #                 empty_set_obj.quantity = 0
    #                 filtered_items.append(empty_set_obj)

    #     user_cardsets_hero = filtered_items

    context = {
        'title': 'Home - Кабинет',
        'form': form,
        'orders': orders,
        'sets': sets,
        # 'cardsets_hero': user_cardsets_hero,
    }

    return render(request, 'users/profile.html', context)

def users_cart(request):
    return render(request, "users/users_cart.html")

#ограничение доступа для неавторизованных пользователей
@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, упешно вышел")
    auth.logout(request)
    return redirect(reverse('main:index'))

saw_mate/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% comment %} расширяем базовый шаблон кнопкой корзины {% endcomment %}
{% comment %} {% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock %} {% endcomment %}
{% comment %} расширяем базовый шаблон кнопкой колоды карт {% endcomment %}
{% block modal_carddeck %}
    {% include "includes/carddeck_button.html" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        {% comment %} Редирект для неавторизованного пользователя когда сработал декоратор {% endcomment %}
                        {% comment %} {% if request.GET.next %}
                            <input type="hidden" name="next" value={{ request.GET.next }}>
                        {% endif %} {% endcomment %}
                        {% comment %} реализация формы входа на сайт с минимальным обращением к бэкенду {% endcomment %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" 
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                            name="username" id="id_username" 
                            placeholder="Введите ваше имя пользователя" 
                            required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" 
                            name="password" id="id_password" 
                            placeholder="Введите ваш пароль" 
                            required>
                        </div>



                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Забыли пароль?</a> | <a href="{% url 'user:registration' %}">Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

saw_mate/users/templates/users/profile copy.html
{% extends "base.html" %}
{% load static %}
{% comment %} подключаем шаблонный тег из приложения carts для передачи карзин пользователя {% endcomment %}
{% load carts_tags %}
{% comment %} подключаем шаблонный тег из приложения card_decks для передачи карзин пользователя {% endcomment %}
{% load carddecks_tags %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="row row-equal-height">
                    <div class="col-md-5">
                        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                            <h3 class="text-center mb-4">Профиль пользователя</h3>
                            <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12 mb-3 text-center">
                                        {% if user.image %}
                                            <img src="{{ user.image.url }}"
                                                alt="Аватар пользователя" 
                                                {% comment %} class="img-fluid rounded-circle" {% endcomment %}
                                                class="card-img-top"
                                                style="max-width: 250px;">
                                        {% else %}
                                            <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                                alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                style="max-width: 150px;">
                                        {% endif %}
                                        <input type="file" class="form-control mt-3" id="id_image"
                                            name='image'
                                            accept="image/*">
                                            {% if form.image.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                            {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_first_name" class="form-label">Имя*</label>
                                        <input type="text" class="form-control" id="id_first_name"
                                            name='first_name'
                                            placeholder="Введите ваше имя" 
                                            value="{{ form.first_name.value }}" 
                                            required>
                                            {% if form.first_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                            {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_last_name" class="form-label">Фамилия*</label>
                                        <input type="text" class="form-control" id="id_last_name"
                                            name='last_name'
                                            placeholder="Введите вашу фамилию" 
                                            value="{{ form.last_name.value }}" 
                                            required>
                                            {% if form.last_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                            {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_username" class="form-label">Имя пользователя*</label>
                                        <input type="text" class="form-control" id="id_username"
                                            name='username'
                                            placeholder="Введите ваше имя пользователя" 
                                            value="{{ form.username.value }}" 
                                            required>
                                            {% if form.username.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                            {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_email" class="form-label">Email*</label>
                                        <input type="email" class="form-control" id="id_email"
                                            name='email'
                                            placeholder="Введите ваш email *youremail@example.com" 
                                            value="{{ form.email.value }}"
                                            required>
                                            {% if form.email.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                            {% endif %}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-dark">Сохранить</button>
                            </form>
                            <div class="col-md-12 mb-3">
                                <h3 class="text-center mb-4">Статистика пользователя</h3>
                                <p>Достижения: {{ user.achievements }} </p>
                                <p>Уровень -  {{ user.level }} </p>
                                <p>Побед -  {{ user.win }} </p>
                                <p>Поражений -  {{ user.lose }} </p>
                                <p>Статус -  {{ user.status }} </p>
                                <p>Деньги -  {{ user.money }} </p>
                            </div>
                        </div>
                    </div>
                    <!-- Корзина -->
                    {% comment %} подключаем шаблонный тег из приложения carts для передачи карзин пользователя {% endcomment %}
                    {% comment %} {% user_carts request as carts %}
                    <div class="col-md-7">
                        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                            <h3 class="text-center mb-4">Корзина</h3>
                            <div class="container" id="cart-items-container">
                                <!-- Разметка корзины -->
                                {% include "carts/includes/included_cart.html" %}
                                <!-- Закончилась разметка корзины -->
                            </div>
                            {% comment %} {% if carts %}
                                <a class="btn btn-dark" href="../orders/create_order.html">
                                    Оформить заказ
                                </a>
                            {% endif %}
                        </div>
                    </div> {% endcomment %}
                    
                    <div class="col-md-7">
                        <!--блок вывода купленных карточек-->
                        {% user_carddecks request as carddecks %}
                        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                            <h3 class="text-center mb-4">Колода карт пользователя</h3>
                            <div class="container" id="carddeck-items-container">
                                {% include "card_decks/includes/included_slider.html" %}
                            </div>
                            <!--сделать кнопку для переноса карточки в набор-->
                            {% if carddecks %}
                                <a class="btn btn-dark" href="{% url 'carddecks:cardset_create' %}">Создать набор карт для игры</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!--Разметка наборов карточек для игры внешняя-->
                <br>
                {% user_cardsets request as cardsets %}
                {% user_setitem request as setitem %}
                {% user_cardsets_hero request as cardsets_hero %}
                <div class="bg-white col-md-20 mx-2 rounded custom-shadow">
                    <!--блок вывода купленных карточек-->
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Наборы карт пользователя</h3>
                        <div class="container" id="cardset-items-container">
                            {% comment %} {% include "card_decks/includes/included_carddeck.html" %} {% endcomment %}
                            {% include "card_decks/includes/included_slider_cardset.html" %}
                        </div>
                        
                        <!--сделать кнопку для переноса карточки в набор-->
                        {% comment %} {% if cardsests %}
                            <a class="btn btn-dark" href="{% url 'carddecks:cardset_create' %}">Создать набор карт для игры</a>
                        {% endif %} {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

saw_mate/users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}
{% comment %} расширяем базовый шаблон кнопкой корзины {% endcomment %}
{% comment %} {% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock %} {% endcomment %}
{% comment %} расширяем базовый шаблон кнопкой колоды карт {% endcomment %}
{% block modal_carddeck %}
    {% include "includes/carddeck_button.html" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action="{% url 'user:registration' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                    name="first_name"
                                    placeholder="Введите ваше имя" required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию" required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя" required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                    name="email"
                                    placeholder="Введите ваш email" required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" id="id_password1"
                                    value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                    name="password1"
                                    placeholder="Введите пароль" required>
                                    {% if form.password1.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" id="id_password2"
                                    value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                    name="password2"
                                    placeholder="Подтвердите пароль" required>
                                    {% if form.password2.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}