saw_mate/card_decks/urls.py
from django.urls import path
from card_decks import views
app_name = 'carddecks'

urlpatterns = [
    path('carddeck_add/', views.carddeck_add, name='carddeck_add'),
    path('carddeck_change/', views.carddeck_change, name='carddeck_change'),
    path('carddeck_remove/', views.carddeck_remove, name='carddeck_remove'),
    path('cardset_create/', views.cardset_create, name='cardset_create'),
    path('cardset_add/', views.cardset_add, name='cardset_add'),
    path('cardset_change/', views.cardset_change, name='cardset_change'),
    path('cardset_activate/', views.cardset_activate, name='cardset_activate'),
    path('cardset_remove/', views.cardset_remove, name='cardset_remove'),
    path('setitem_remove/', views.setitem_remove, name='setitem_remove'),
]

saw_mate/main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),

]

saw_mate/saw_mate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from saw_mate import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("cards.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("carddeck/", include("card_decks.urls", namespace="carddeck")),
    path("game/", include("games.urls", namespace="game")),
]

#для отладки запросов к БД
if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saw_mate/card_decks/models.py
from django.db import models

from cards.models import Products

from users.models import User

#from card_decks.models import CardDeck, CardSet



#описание общей колоды купленных карточек (аналог корзины)

class CardDeckQueryset(models.QuerySet):
    #вывод количества купленных карточек
    def total_quantity(self):
        if self:
            return sum(carddeck.quantity for carddeck in self)
        return 0

class CardDeck(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    #если пользователь не авторизован то данные из корзины будут вноситься по ключу сессии
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    #set_of_cards = models.ForeignKey(to='CardSet', on_delete=models.CASCADE, null=True, verbose_name='Набор карт')


    class Meta:
        db_table = 'carddeck'
        verbose_name = 'Колода карт'
        verbose_name_plural = 'Колоды карт'

    #переопределим менеджер objects
    objects = CardDeckQueryset().as_manager()

    def __str__(self):
        if self.user:
            return f'Колода {self.user.username} | Товар {self.product.name} | Количество {self.quantity}'

        return f'Анонимная колода | Товар {self.product.name} | Количество {self.quantity}'

# второй вариант набора карт (аналог заказа)
class SetItemQueryset(models.QuerySet):

    def total_quantity(self):
        if self:
            return sum(set_item.quantity for set_item in self)
        return 0
# модель для описания набора карточек
class Set(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания колоды")
    active = models.BooleanField(default=False, verbose_name='Активная колоды')

    class Meta:
        db_table = 'set'
        verbose_name = 'Набор карт версия 2'
        verbose_name_plural = 'Наборы карт версия 2'
    
    def __str__(self):
        return f"Набор карточек (версия 2) № {self.pk}"
# модель для карточек в наборе
class SetItem(models.Model):
    set = models.ForeignKey(to=Set, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name='Карточка в наборе (версия 2)', default=None)
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    class Meta:
        db_table = 'set_item'
        verbose_name = 'Карточка в наборе (версия 2)'
        verbose_name_plural = 'Карточки в наборе (версия 2)'

    objects = SetItemQueryset.as_manager()

    def __str__(self):
        return f"Карточка {self.product} | Набор № {self.set.pk}"

saw_mate/card_decks/forms.py
#форма не связанная с моделью
from django import forms
import re

class CreateCardsetForm(forms.Form):
    cardset_name = forms.CharField()
    #cardset_description = forms.CharField()
    cardset_status = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
        ],)

saw_mate/card_decks/views.py
from django.db.models import Q
from django.forms import ValidationError
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from card_decks.models import CardDeck, Set, SetItem
from card_decks.utils import get_user_carddecks, get_user_setitem, get_user_cardsets, get_user_cardsets_hero
from card_decks.forms import CreateCardsetForm
from django.contrib import messages
from django.db import transaction
from django.shortcuts import get_object_or_404

from cards.models import Products
#упрощаяем работу с покупкой карточек
def carddeck_add(request):
    #получает с фронта id купленной карточки
    product_id = request.POST.get("product_id")
    try:
        product = Products.objects.get(id=product_id)
    except Products.DoesNotExist:
        return JsonResponse({"error": "Товар с указанным идентификатором не найден."}, status=400)
    #получаем объект товара в корзину
    product = Products.objects.get(id=product_id)
    if request.user.is_authenticated:
        #запрашиваем корзину пользователя по определенному товару
        carddecks = CardDeck.objects.filter(user=request.user, product=product)
        #если товар уже есть в корзине то увеличиваем количество товара на 1 и сохраняем корзину
        if carddecks.exists():
            carddeck = carddecks.first()
            if carddeck:
                carddeck.quantity += 1
                carddeck.save()
            #если корзина по доавбляемому товару не найдена то создаем ее
        else:
            CardDeck.objects.create(user=request.user, product=product, quantity=1)
    #добавление товара в корзину для неавторизованного пользователя
    else:
        carddecks = CardDeck.objects.filter(
            session_key=request.session.session_key, product=product)
        if carddecks.exists():
            carddeck = carddecks.first()
            if carddeck:
                carddeck.quantity += 1
                carddeck.save()
        else:
            CardDeck.objects.create(session_key=request.session.session_key, product=product, quantity=1)
    #работа с jquery для перерисовки корзины без обновления страницы
    #получаем все корзины пользователя с помошью метода из файла utils.py
    user_carddeck = get_user_carddecks(request)
    #преобразуем в строку разметку корзины пользователя с передачей в разметку контекста user_cart и request
    carddeck_items_html = render_to_string(
        #формируем часть разметки шаблона в виде строки и контекст в виде словаря для перерисовки с помощью jquery
        "card_decks/includes/included_carddeck.html", {"carddecks": user_carddeck}, request=request)
    #формируем контекст для передачи в виде json словаря
    response_data = {
        #передаем текст оповещения
        "message": "Карта добавлена в колоду",
        #передаем разметку содержимого корзины для переотрисовки с помощью jquery
        "carddeck_items_html": carddeck_items_html,
    }
    return JsonResponse(response_data)

# def carddeck_change(request):
#     #получаем данные из post запроса
#     carddeck_id = request.POST.get("carddeck_id")
#     #получаем с фронтенда количество товара которое должно быть в корзине
#     quantity = request.POST.get("quantity")
#     #получаем экзепляр объекта корзины из модели по id
#     carddeck = CardDeck.objects.get(id=carddeck_id)
#     #Формируем данные для контекста - записываем количество товара в корзине
#     carddeck.quantity = quantity
#     carddeck.save()
#     update_quantity = carddeck.quantity
#     #работа с jquery для перерисовки корзины без обновления страницы
#     #получаем все корзины пользователя с помошью метода из файла utils.py
#     carddeck = get_user_carddecks(request)
#     carddeck_items_html = render_to_string(
#         #формируем часть разметки шаблона в виде строки и контекст в виде словаря для перерисовки с помощью jquery
#         "card_decks/includes/included_carddeck.html", {"carddecks": carddeck}, request=request
#     )
#     #собираем контекст для передачи в jquery
#     response_data = {
#         "message": "Количество карт в колоде изменено",
#         "carddeck_items_html": carddeck_items_html,
#         "quantity": update_quantity,
#     }
#     return JsonResponse(response_data)

#переносим карту из колоды в набор
def carddeck_change(request):
    #работаем с набором карт пользователя
    #получаем данные из post запроса о колоде пользователя
    carddeck_id = request.POST.get("carddeck_id")
    #получаем экзепляр объекта набора карт из модели по id
    carddeck = CardDeck.objects.get(id=carddeck_id)
    #получим количество объекта из модели
    #quantity = setitem.quantity
    if carddeck.quantity >= 1:
        carddeck.quantity -=1
        carddeck.save()

    cardset_id = request.POST.get("cardset_id")
    print('набор карт')
    print(cardset_id)
    cardset, created = Set.objects.get_or_create(id=cardset_id, user=request.user)
    
    setitem, created = SetItem.objects.get_or_create(set=cardset, product=carddeck.product, defaults={"quantity": 1})
    setitem.quantity += 1
    setitem.save()

    #работаем с перерисовкой шаблонов
    #получаем все наборы карт пользователя с помошью метода из файла utils.py
    user_cardset = get_user_cardsets(request)
    user_cardsets_hero = get_user_cardsets_hero(request)
    #преобразуем в строку разметку набора карт пользователя с передачей в разметку контекста
    cardset_items_html = render_to_string(
        "card_decks/includes/included_slider_cardset.html", {"cardsets": user_cardset}, {"cardsets_hero": user_cardsets_hero}, request=request)
    #получаем колоду пользователя с помошью метода из файла utils.py
    user_carddeck = get_user_carddecks(request)
    #преобразуем в строку разметку колоды пользователя с передачей в разметку контекста
    carddeck_items_html = render_to_string(
        #формируем часть разметки шаблона в виде строки и контекст в виде словаря для перерисовки с помощью jquery
        "card_decks/includes/included_slider.html", {"carddecks": user_carddeck}, request=request)
    #собираем контекст для передачи измений в наборе карт в jquery
    response_data = {
        "message": "Карточка успешно убрана из набора и возвращена в колоду карт",
        "cardset_items_html": cardset_items_html,
        "carddeck_items_html": carddeck_items_html,
    }
    return JsonResponse(response_data)

#сделать как продажу карточки чтобы получить деньги для покупки новой
def carddeck_remove(request):
    #получаем данные из post запроса
    carddeck_id = request.POST.get("carddeck_id")
    #собираем данные для контекста
    #получаем экзепляр объекта корзины из модели по idcart_change
    carddeck = CardDeck.objects.get(id=carddeck_id)
    quantity = carddeck.quantity
    carddeck.delete()
    #работа с jquery для перерисовки корзины без обновления страницы
    #получаем все корзины пользователя с помошью метода из файла utils.py
    user_carddeck = get_user_carddecks(request)
    carddeck_items_html = render_to_string(
        #формируем часть разметки шаблона в виде строки и контекст в виде словаря для перерисовки с помощью jquery
        # "card_decks/includes/included_carddeck.html", {"carddecks": user_carddeck}, request=request)
        "card_decks/includes/included_slider.html", {"carddecks": user_carddeck}, request=request)
    #собираем контекст для передачи в jquery
    response_data = {
        "message": "Карта удалена из колоды",
        "carddeck_items_html": carddeck_items_html,
        "quantity_deleted": quantity,
    }
    return JsonResponse(response_data)

#@login_required
def cardset_create(request):
    if request.method == 'POST':
        try:
            with transaction.atomic():
                user = request.user
                Set.objects.create(user=user)
                messages.success(request, 'Новый набор карт создан')
        except ValidationError as e:
            messages.error(request, str(e))
        # Получаем все наборы карт пользователя с помощью метода из файла utils.py
        user_cardset = get_user_cardsets(request)
        # Преобразуем в строку разметку набора карт пользователя с передачей в разметку контекста
        cardset_items_html = render_to_string("card_decks/includes/included_cardset_item.html", {"cardsets": user_cardset}, request=request)
        # Собираем контекст для передачи изменений в наборе карт в jQuery
        response_data = {
            "message": "Набор карт успешно создан и отрисован",
            "cardset_items_html": cardset_items_html,
        }
        return JsonResponse(response_data)
    return JsonResponse({"error": "Invalid request method"}, status=400)

#@login_required
def cardset_add(request):
    if request.method == 'POST':
        form = CreateCardsetForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    carddeck_items = CardDeck.objects.filter(user=user)

                    if carddeck_items.exists():
                        cardset = Set.objects.create(
                            user=user,
                            active=form.cleaned_data['cardset_status'],
                        )
                        #добавляем карточки в набор
                        for carddeck_item in carddeck_items:
                            product = carddeck_item.product
                            name = carddeck_item.product.name
                            quantity = carddeck_item.quantity

                            SetItem.objects.create(
                                set = cardset,
                                product = product,
                                #name = name,
                                quantity = quantity,
                            )
                            #меняем количество карточек в колоде - будем также менять в обратную сторону при корректировке набора карт

saw_mate/card_decks/templates/card_decks/includes/included_carddeck.html
{% load static %}
{% comment %} переиспользуемый блок для визуализации купленных карточек модели CardDeck {% endcomment %}
<div class="card mb-3 text-bg-light shadow-lg">
    <h5>Проверка приложения card_deck</h5>
    {% for carddeck in carddecks %}
        <div class="card-header">
            <h5 class="card-title">{{ carddeck.product.name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <p class="card-title">{{ carddeck.product.name }} </p>
                    </div>
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement-carddeck"
                                    data-carddeck-id="{{ carddeck.id }}" 
                                    data-carddeck-change-url="{% url 'carddeck:carddeck_change' %}">
                                    {% csrf_token %}
                                    -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ carddeck.quantity }}"
                                readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment-carddeck"
                                    data-carddeck-id="{{ carddeck.id }}" 
                                    data-carddeck-change-url="{% url 'carddeck:carddeck_change' %}">
                                    {% csrf_token %}
                                    +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0">
                        {% comment %} <p>x {{ carddeck.product.sell_price }} = </p> {% endcomment %}
                    </div>
                    {% comment %} <div class="col p-0"><strong>{{ carddeck.products_price }} $</strong></div> {% endcomment %}
                    <div class="col p-0">
                        <a href="{% url 'carddeck:carddeck_remove' %}" class="remove-from-carddeck" 
                        data-carddeck-id="{{ carddeck.id }}">
                        {% csrf_token %}
                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                alt="Catalog Icon" width="16" height="16">
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}

</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carddeck.total_quantity }}</strong> Всего карточек пользователя</p>
        <h4 class="float-left"><strong>{{ carddeck.total_quantity }} $</strong></h4>
    </div>
</div>

saw_mate/card_decks/templates/card_decks/includes/included_cardset_item.html
<!--Подключаемый шаблон наборов карт-->
{% load static %}
{% load cards_tags %}
{% load carddecks_tags %}
<div class="card mb-3 text-bg-light shadow-lg">
    <!--Список наборов карт для игры-->
    <ul class="cardset_list">
        {% for set in cardsets %}
            <div>
                <li>
                    <div class="cardset_list_item">
                        <h3 class="product-delete">
                            <a href="{% url 'carddeck:cardset_remove' %}" class="remove-cardset"
                            data-cardset-id="{{ set.id }}"
                            {% csrf_token %}
                                <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                    alt="Catalog Icon" width="16" height="16">
                            </a>
                        </h3>
                        <!--редактирование набора карт и установка набора активным для игры-->
                        <button 
                            data-url="{% url "carddeck:cardset_change" %}"
                            class="btn btn-secondary {% if set.id|stringformat:"s" == current_set_id|stringformat:"s" %}btn-purple{% else %}btn-dark{% endif %} cardset_change"
                            {% comment %} class="btn btn-secondary {% if current_set_active == True %}btn-purple{% else %}btn-dark{% endif %} cardset_change"  {% endcomment %}
                            type="button"
                            data-cardset-id="{{ set.id }}">
                            {% csrf_token %}
                            Набор № {{ set.id }}
                        </button>
                        {% comment %} карточек в наборе - {{ set.setitem_set.total_quantity }},  {% endcomment %}
                        {% comment %} набор создан - {{ set.created_timestamp }}, {% endcomment %}
                        {% comment %} current_set_id - {{ current_set_id }}, {% endcomment %}
                    </div>
                </li>
            </div>
        {% endfor %}
        <br>
        <div>
            <button
                data-url="{% url 'carddeck:cardset_create' %}"
                class="btn btn-dark btn-sm cardset_create"
                type="button">
                {% comment %} data-carddeck-id="{{ carddeck.id }}"  {% endcomment %}
                {% csrf_token %}
                +
            </button>
        </div>
    </ul>

    <br>
    <br>
    <!--Карты в активном наборе-->
    {% comment %} <ul class="hero_card_list"> {% endcomment %}
    <ul class="action_card_list">
        {% for item in setitems %}
            {% comment %} <li class="hero_card_list_item item{% if forloop.first %} first{% elif forloop.last %} last{% endif %}"> {% endcomment %}
            <li class="action_card_list_item">
                {% comment %} <div class="content1"> {% endcomment %}
                <div class="content">
                
                    <div class="card-img">
                        {% if item.product.image %}
                        <img src="{{ item.product.image.url }}" class="card-img-top" alt="Карточка персонажа">
                            {% comment %} <div class="rounded product-box" data-static-url="{{ item.product.image.url }}"></div> {% endcomment %}
                            {% comment %} <div class="texture-paths" style="display: none;"
                                data-product = "{{ item.product.image.url }}"
                                data-cover = "{% static 'deps/js/assets/card2.png' %}"
                            ></div> {% endcomment %}
                        {% else %}
                            <img src="{% static "deps/images/empty3.jpg" %}" class="card-img-top" alt="Карточка персонажа" style="max-height: 265px; overflow: auto">
                        {% endif %}
                    </div>
                    <div class="action_cardset">
                        <!--Перенос карточки в колоду-->
                        <p class="cardset_change">
                            <a href="{% url 'carddeck:cardset_change' %}" class="add-to-carddeck"
                            data-cardset-id="{{ set.id }}"
                            data-setitem-id="{{ item.id }}">
                            {% csrf_token %}
                                <img class="mx-1" src="{% static "deps/icons/carddecks_b.svg" %}"
                                    alt="Catalog Icon" width="16" height="16">
                            </a>
                        </p>
                        <p class="cardset_change">{{item.product.name}}</p>
                        <!--Перенос карточки из колоды-->
                        <p class="product-delete">
                            <a href="{% url 'carddeck:setitem_remove' %}" class="remove-from-cardset"
                            data-cardset-id="{{ set.id }}"
                            data-setitem-id="{{ item.id }}">
                            {% csrf_token %}
                                <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                    alt="Catalog Icon" width="16" height="16">
                            </a>
                        </p>
                    </div>
                    {% comment %} <p>product sell_price: {{ item.product.sell_price }}</p>
                    <p>category name: {{ item.product.category.name }}</p>
                    <p>set id: {{ set.id }}</p>
                    <p>item id: {{ item.id }}</p>
                    <p>item quantity: {{ item.quantity }}</p> {% endcomment %}
                </div>
            </li>
        {% endfor %}

</div>
<br>
{% comment %} активировать набор карт {% endcomment %}
<button 
    data-url="{% url "carddeck:cardset_activate" %}"
    class="btn btn-secondary {% if current_set_active == True %}disabled{% else %}btn-dark{% endif %} cardset_activate" 
    type="button"
    data-cardset-id="{{ current_set_id }}">
    {% csrf_token %}
    Активировать набор
</button>
<p>set active: {{ current_set_active }}</p>
<p>setitems: {{ setitems }}</p>

saw_mate/card_decks/templates/card_decks/includes/included_catalog.html
{% load static %}
{% load cards_tags %}
{% load carddecks_tags %}

<style>
    .carddeck-container {
        max-height: 400px; /* Высота контейнера, которая будет ограничивать область отображения */
        overflow-y: auto; /* Добавление вертикальной полосы прокрутки */
    }
</style>

    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>
        {% comment %} Если используется поиск то берется маршрут name='search' иначе маршрут name='index' {% endcomment %}
        {% comment %} <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == 'default'%}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form> {% endcomment %}
    </div>
    {% comment %} Результат поиска {% endcomment %}
    {% if request.GET.q %}
    <h3 class="mt-4">Результат поиска по запросу {{ request.GET.q }}</h3>
        {% if not cards %}
            <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
            <h2 class="mt-4">По запросу ничего не найдено</h2>
        {% endif %}
    {% endif %}
    {% comment %} каталог купленных карт {% endcomment %}
    <div class="row carddeck_catalog_container">
        {% for carddeck in carddecks %}
            <div class="col-lg-6 col-md-6 col-sm-12 p-3">
            {% comment %} <div class="col-lg-4 col-md-6 p-4"> {% endcomment %}
                <div class="card border-primary rounded custom-shadow">
                    <div class="content1">
                        <div class="card-img">
                            {% if carddeck.product.image %}
                                {% comment %} <img src="{{ carddeck.product.image.url }}" class="card-img-top" alt="Карточка колоды"> {% endcomment %}
                                <div class="rounded product-box" data-static-url="{{ carddeck.product.image.url }}"></div>
                                <div class="texture-paths" style="display: none;"
                                    data-product = "{{ carddeck.product.image.url }}"
                                    data-cover = "{% static 'deps/js/assets/card2.png' %}"
                                ></div>
                            {% else %}
                                <img src="{% static "deps/images/empty3.jpg" %}" class="card-img-top" alt="Карточка персонажа" style="max-height: 265px; overflow: auto">
                            {% endif %}
                        </div>
                        <div class="action_carddeck">
                            <!--Перенос карточки в колоду-->
                            <p class="carddeck_change">
                                <a href="{% url 'carddeck:carddeck_change' %}" class="add-to-cardset" data-carddeck-id="{{ carddeck.id }}">
                                    {% csrf_token %}
                                    <img class="mx-1" src="{% static "deps/icons/cardsets.svg" %}" alt="Catalog Icon" width="16" height="16">
                                </a>
                            </p>
                            <p class="carddeck_change">{{carddeck.product.name}}</p>
                            <!--Перенос карточки из колоды-->
                            <p class="product-delete">
                                <a href="{% url 'carddeck:carddeck_remove' %}" class="remove-from-carddeck" data-carddeck-id="{{ carddeck.id }}">
                                    {% csrf_token %}
                                    <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}" alt="Catalog Icon" width="16" height="16">
                                </a>
                            </p>
                        </div>
                        {% comment %} <p>carddeck sell_price: {{ carddeck.product.sell_price }}</p> {% endcomment %}
                        {% comment %} <p>category name: {{ carddeck.product.category.name }}</p> {% endcomment %}
                        {% comment %} <p>carddeck id: {{ carddeck.id }}</p> {% endcomment %}
                        {% comment %} <p>carddeck quantity: {{ carddeck.quantity }}</p> {% endcomment %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>